language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then mvn clean source:jar javadoc:javadoc deploy --settings travis_settings.xml; fi'
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then mvn clean verify; fi'

# travis encrypt -r bootique/bootique-jersey-client "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r bootique/bootique-jersey-client "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "GDH3uJ0Pa5R1/L01RXcLMjcKZpZerG1XBazTMV+vesxO3ws0gfABg35jLHq2mUHCjkptEPY4Z/P5gUl7Umt+yY0MwfD2PD/IPi2v+j40ajm/u6qwKzUcnFDE9HqJ6wMiEdElKiPwopcsmdqR6D7CdInHjaf82zlvIDB35pksfdCfjf7o2VF0KsfcnIhYEx0nBgsGv6Y8qqXBi52NAoA4St2b0ICTUDgajuBFlFnviPPaJG+kqekF+lCaHdyY8dhdGuTJAFAaa1jsGhtlM1QMI4kPMq0UDmtiF0OsnXwqWFPXOCH/QpPzn1Owsx0+sdoVxvUnzwL0hNxKil6au4lrYMigO3eG8QMvv+KSvbaOXP76B5jwds2siHaTTGQCv/AUb2jUDeqUnPBCnPteZGWdQKLXe6bT8dbjvMGNxAow4+03N/8WI4rj4YMBPq1zh8vcJ/haqy/OASKX0qDMAfjQ0ZPaR8VNmHyblziS6FZcxVkohpBuSMGGFzcxq90UNnTArYlXtx7IkgQuT9d9Xh061kj5lixoJMat3P8G5dY7491eviRQGOQ+iRzYWTaxuvfsLohdJjAgMOR6V40qmnhkrsRC4ZX57LTyNPjnG2+TbGg5IwWj4DXEw/pRL/109NGo/W+cEO/IEe6GFUPi0g1mGe2LwF9K9MacIomE0RgnyEk="
    - secure: "c6IST8Lp74xGyBgDOQNzJ+f3OXk0LoI8D3tsEgh1U3rLvXFNIu7aOa0Kmghk4Z1WvQ7JpY/iF13l7qM4VGnouX2yZ9iAzgfwIBWiGrB9xcOyl3ztBMno0V72iUaCrNl8VtnQwNH0j+YQ4mRGAtvvwVOkWtFh23WuuCzvlSE7IVRLmQ0E07ifoOJ+N3DlV4lEIMw47hvVgGE+be4N56KamZk8t6k4jLiB5vM3GRr9QSRBQzDXYAzMOOyyrHrpSbT7IUcdABa+qM8iiohnqG8WDtwtpZO/6PGMU/zuc17Vw6DxW5OKvvak66s9lKcP5/nnISC/z+WiaeqyllAC82r1Byztb1V3RE62ff8AHc/yiu9nB9ZPfiuovy4Ra6fKIVE3Zo1HlyRoUsE80kwyOkzu1FcXovQsce4uqF2xgKbqU9Cj6uoIA0jl3jp5n9IUJzT8IvyLRIDKyjNZJ1CKxmV9JHGk+BrflyXGdrsI/7YrJAfhzNQfoe0VtG0QsoxkU6yWXAMh91+3MDemmZMyaDMaaDsRASjZRA8kWzO/T9zCRAJWR0G8X42HSwqdcjIZIVify/Wj5LExnFvDIndjGAVrvvOg3g9WhdShRlo9cwxBzqZCDJjsoYruExssTtWlTnCvorAH0qXl9bVd9hPr+w1FMPLzwSQIQxCvdmQ2TFs7lr8="
